const User = require ("./user")
const Scooter = require ("./scooter")
const ScooterHire = require ("./scooterHire")

user1 = new User ("James", 20, 150.00)
user2 = new User ("Mohammed", 21, 130.00)
user3 = new User ("Emily", 19, 140.00)
user4 = new User ("Philip", 22, 140.00)
user5 = new User ("Hannah", 21, 150.00)

scooter1 = new Scooter ("Scooter01", "Canary Wharf", "Fixed", 100)
scooter2 = new Scooter ("Scooter02", "Canary Wharf", "Fixed", 70)
scooter3 = new Scooter ("Scooter03", "Mile End", "Broken", 100)
scooter4 = new Scooter ("Scooter04", "Mile End", "Fixed", 100)
scooter5 = new Scooter ("Scooter05", "Whitechapel", "Broken", 40)

hire1 = new ScooterHire()
hire1.hireScooter(scooter1, user1)
//console.log(hire1)
hire1.reportBroken(scooter1)
hire1.return(user1, scooter1, "Mile End")
console.log(scooter1)
//console.log(user1)
//console.log(User.users)